"""Add session_id and user_id columns

Revision ID: afc952b5d320
Revises: bf65eb265dbf
Create Date: 2026-01-28 21:04:57.787296

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'afc952b5d320'
down_revision = 'bf65eb265dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
