"""init_db_schema

Revision ID: bf65eb265dbf
Revises: 
Create Date: 2026-01-24 09:42:18.477571

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf65eb265dbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sql_output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_queries_chain'), 'user_queries', ['chain'], unique=False)
    op.create_index(op.f('ix_user_queries_id'), 'user_queries', ['id'], unique=False)
    # Drop old table only if exists (for migration from old schema)
    op.execute('DROP TABLE IF EXISTS userquery')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userquery',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_input', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sql_output', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('userquery_pkey'))
    )
    op.drop_index(op.f('ix_user_queries_id'), table_name='user_queries')
    op.drop_index(op.f('ix_user_queries_chain'), table_name='user_queries')
    op.drop_table('user_queries')
    # ### end Alembic commands ###
